version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
      time: "08:30"
      timezone: Etc/UTC
    groups:
      rust-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "08:30"
      timezone: Etc/UTC
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
